name: Fly Deploy
on:
  push:
    branches:
      - main
      - master
jobs:
  test-and-lint:
    name: Testing app and Lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Lint with ruff
        run: |
          # stop the build if there are Python syntax errors or undefined names
          # ruff --format=github --ignore E501 --select=E9,F63,F7,F82 --target-version=py310 .
          # default set of ruff rules with GitHub Annotations
          ruff --format=github --exclude ./oc_lettings_site/migrations --ignore E501 --target-version=py310 .
      - name: Test with pytest
        run: |
          pytest

  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    needs: test-and-lint
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}